import type {Metadata} from 'next';
import {Mulish} from 'next/font/google';
import './globals.css';
import {Header} from '@/components/Header';
import {GlobalWrapper} from '@/components/GlobalWrapper';
import {Subheader} from '@/components/Subheader';

const mulish = Mulish({subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={mulish.className}>
        <Header />
        <Subheader />
        <GlobalWrapper.Container>
          <GlobalWrapper.Content>{children}</GlobalWrapper.Content>
        </GlobalWrapper.Container>
      </body>
    </html>
  );
}
